AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/LineLength:
  Enabled: false

Style/MethodLength:
  Max: 20
